config/routes.rb
Rails.application.routes.draw do
  resources :redirections do
      collection do
          put 'update_all'
      end
  end

  get 'welcome/index'

  root 'welcome#index'

end

app/models/redirection.rb
class Redirection < ActiveRecord::Base
    before_create :default_values

    def default_values
        self.active ||= true
    end
    
    def self.update_attr(active)
        all = Redirection.all.pluck(:id)
        inactive = all - active
        update_states(inactive,false)
        update_states(active,true)
    end

    private

        def self.update_hyperlinks()
        
        end

        def self.update_states(array,state)
            Redirection.where(:id => array).update_all(:active => state)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/redirections_controller.rb
class RedirectionsController < ApplicationController
  def index
      @redirections = Redirection.all
  end

  def new
  end
  
  def create
      if Redirection.create(create_params)
        flash[:notice] = "Successfully added"
        redirect_to redirections_path
      else
        render :action => 'new'
      end
  end

  def update_all
    Redirection.update_attr(params[:active_ids])  
    redirect_to :redirections
  end
  
  def show
  end

  def destroy
    Redirection.find(params[:id]).destroy
    redirect_to :redirections
  end

  private 
    def create_params
        params.require(:redirection).permit(:country,:hyperlink,:active)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :locate 
  def index
  end
  
  private
     def locate
        @geoip ||= GeoIP.new(::Rails.root.join('db','GeoIP.dat'))  
        remote_ip = request.remote_ip 
        if remote_ip != "127.0.0.1"
            country = @geoip.country(remote_ip)
            if country != nil
                redirect(country[:country_name])
            end
        elsif !Redirection.all.empty?
            redirect(Redirection.first.country)
        end
     end

     def redirect(current_country)
        pos = Redirection.where(country:current_country).first
        if pos != nil && pos[:active]
            hyperlink = pos[:hyperlink]
            redirect_to hyperlink.to_s
        end
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/redirection_helper.rb
module RedirectionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redirecter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/redirections/index.html.erb
<div class="row">
    <%= form_tag update_all_redirections_path, :method => :put do %>
        <h4 class="col-md-8">Locations</h4>
        <div class="col-md-2">
        <%= link_to 'Add country', new_redirection_path, class:"btn btn-default pull-right" %>
        </div>
        <div class="col-md-2">
		    <%= submit_tag "Update",class: "btn btn-default" %>
        </div>
    </div>
        <table class="table">
            <tr>
                <th>Country</th>
                <th>Site</th> 
                <th>Active</th>
            </tr>
            <% for location in @redirections %>
                 <tr>
                    <td><%= location.country %></td>
                    <td><%= url_field_tag "hyperlink_ids[#{location.id}]", location.hyperlink%></td>
                    <td><%= check_box_tag "active_ids[]",location.id,location.active %></td>
                    <td><%= link_to 'Remove', redirection_path(location),
                                      method: :delete,
                                      data: { confirm: 'Are you sure?' } %></td>
                </tr>
			<%end%>
        </table>
     <% end %>
</div>

app/views/redirections/new.html.erb
<style>
.margin {
    margin-top:10px;
}
.well
{       
    position:absolute;      
    top: 30%;
    margin-top:-100px; /* negative number 1/2 height */
    outline:1px solid #CCC;
}
</style>
    <div class="col-md-6 col-md-offset-3 well">
        <%= form_for (Redirection.new) do |f| %>
            <div class="form-group margin">
                <h4 class="control-labeli col-sm-offset-3 col-sm-8"><strong>Add configuration for a new country<strong></h4>
            </div>
            <div class="form-group margin">
                    <div class="col-sm-3">
                        <%= f.label "Select a Country: ", class:"control-label" %>
                    </div>
                    <div class="col-sm-9">
                        <%= country_select("redirection", "country",{},{class:"form-control"}) %> 
                    </div>
            </div>
            <div class="form-group margin">
                    <div class="col-sm-3">
                    <%= f.label "Redirect To: ", class:"control-label" %>
                    </div>
                    <div class="col-sm-9">
                        <%=f.url_field(:hyperlink,{class:"form-control"})%>
                    </div>
            </div>
            <div class="form-group margin">
                <div class="col-sm-offset-8 col-sm-4">
                    <%= f.submit class:' btn btn-success pull-right' do %>
                        <i class="icon-up-arrow icon-white"></i>
                    <%end %>
                </div>
            </div>
        <% end %>
    </div>

app/views/welcome/index.html.erb
<div class="container">
  <h2>Welcome</h2>
  <p>Work in progress!</p>
  <form role="form">
    <div class="form-group">
      <label for="usr">Name:</label>
      <input type="text" class="form-control" id="usr">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd">
    </div>
  </form>
</div>